name: CI for general build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: config
      run: cmake -B ${{github.workspace}}/build -DSPM_BUILD_TEST=ON

    - name: build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: test
      working-directory: ${{github.workspace}}/build
      run: ctest
